from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class SourceDefinition:
    source_id: str
    owner_name: str
    base_url: str
    docs_url: str
    access_method: str
    auth_type: str
    cadence_tier: str
    storage_mode: str = "aggregate"
    identity_mode: str = "none"
    content_policy: str = "Store only the minimum fields needed for provenance and aggregation."
    supported_countries: tuple[str, ...] = ("KR",)
    supported_languages: tuple[str, ...] = ("ko",)


SOURCES: tuple[SourceDefinition, ...] = (
    SourceDefinition(
        "SRC_MOIS_ADMIN_CODES",
        "행정안전부",
        "https://www.mois.go.kr/cmm/fms/FileDown.do",
        "https://www.mois.go.kr/frt/bbs/type001/commonSelectBoardArticle.do?bbsId=BBSMSTR_000000000052&nttId=122595",
        "zip_file",
        "public",
        "E",
    ),
    SourceDefinition(
        "SRC_NAVER_TREND",
        "NAVER Cloud",
        "https://naveropenapi.apigw.ntruss.com/datalab/v1/search",
        "https://api.ncloud-docs.com/docs/ai-naver-searchtrend-search",
        "json_api",
        "client_credentials",
        "B",
    ),
    SourceDefinition(
        "SRC_YOUTUBE",
        "Google",
        "https://www.googleapis.com/youtube/v3",
        "https://developers.google.com/youtube/v3",
        "json_api",
        "api_key",
        "B",
        supported_languages=("ko", "en", "ja", "zh-CN"),
    ),
    SourceDefinition(
        "SRC_INSTAGRAM",
        "Meta",
        "https://graph.facebook.com",
        "https://developers.facebook.com/docs/instagram-platform/instagram-api-with-facebook-login/hashtag-search",
        "json_api",
        "oauth_app_review",
        "A",
        supported_countries=(),
        supported_languages=(),
    ),
    SourceDefinition(
        "SRC_FACEBOOK",
        "Meta",
        "https://graph.facebook.com",
        "https://developers.facebook.com/docs/graph-api/",
        "json_api",
        "oauth_app_review",
        "A",
        supported_countries=(),
        supported_languages=(),
    ),
    SourceDefinition(
        "SRC_TIKTOK",
        "TikTok",
        "https://open.tiktokapis.com/v2/research",
        "https://developers.tiktok.com/products/research-api/",
        "json_api",
        "approved_research_project",
        "A",
        supported_countries=(),
        supported_languages=(),
    ),
    SourceDefinition(
        "SRC_X",
        "X",
        "https://api.x.com/2/tweets/counts/recent",
        "https://docs.x.com/x-api/posts/search/introduction",
        "json_api",
        "paid_bearer_token",
        "A",
        supported_countries=(),
        supported_languages=(),
    ),
    SourceDefinition(
        "SRC_REDDIT",
        "Reddit",
        "https://oauth.reddit.com",
        "https://support.reddithelp.com/hc/en-us/articles/16160319875092-Reddit-Data-API-Wiki",
        "json_api",
        "oauth_approval",
        "A",
        supported_countries=(),
        supported_languages=("en",),
    ),
    SourceDefinition(
        "SRC_WEIBO",
        "Sina Weibo",
        "https://api.weibo.com/2",
        "https://open.weibo.com/wiki/API",
        "json_api",
        "approved_application",
        "A",
        supported_countries=("CN",),
        supported_languages=("zh-CN",),
    ),
    SourceDefinition(
        "SRC_DOUYIN",
        "Douyin",
        "https://open.douyin.com",
        "https://developer.open-douyin.com/docs/resource/zh-CN/dop/develop/openapi/account-permission/",
        "json_api",
        "approved_application",
        "A",
        supported_countries=("CN",),
        supported_languages=("zh-CN",),
    ),
    SourceDefinition(
        "SRC_XIAOHONGSHU",
        "Xiaohongshu",
        "https://adapi.xiaohongshu.com",
        "https://adapi.xiaohongshu.com/doc",
        "json_api",
        "restricted_partner",
        "A",
        supported_countries=("CN",),
        supported_languages=("zh-CN",),
    ),
    SourceDefinition(
        "SRC_LINE",
        "LINE Yahoo",
        "https://api.line.me",
        "https://developers.line.biz/en/docs/messaging-api/get-insight/",
        "json_api",
        "official_account_owner_only",
        "A",
        supported_countries=("JP", "TW"),
        supported_languages=("ja", "zh-TW"),
    ),
    SourceDefinition(
        "SRC_KTO_RESOURCE_DEMAND",
        "한국관광공사",
        "https://apis.data.go.kr/B551011/AreaTarResDemService",
        "https://www.data.go.kr/data/15152138/openapi.do",
        "json_xml_api",
        "public_data_service_key",
        "C",
    ),
    SourceDefinition(
        "SRC_KTO_REGIONAL_VISITORS",
        "한국관광공사",
        "https://apis.data.go.kr/B551011/DataLabService",
        "https://www.data.go.kr/data/15101972/openapi.do",
        "json_xml_api",
        "public_data_service_key",
        "C",
    ),
    SourceDefinition(
        "SRC_KTO_DEMAND_INTENSITY",
        "한국관광공사",
        "https://apis.data.go.kr/B551011/AreaTarDemDsService",
        "https://www.data.go.kr/data/15151868/openapi.do",
        "json_xml_api",
        "public_data_service_key",
        "C",
    ),
    SourceDefinition(
        "SRC_KTO_DIVERSITY",
        "한국관광공사",
        "https://apis.data.go.kr/B551011/AreaTarDivService",
        "https://www.data.go.kr/data/15151365/openapi.do",
        "json_xml_api",
        "public_data_service_key",
        "C",
    ),
    SourceDefinition(
        "SRC_TOUR_KO",
        "한국관광공사",
        "https://apis.data.go.kr/B551011/KorService2",
        "https://www.data.go.kr/data/15101578/openapi.do",
        "json_xml_api",
        "public_data_service_key",
        "C",
    ),
    SourceDefinition(
        "SRC_TOUR_EN",
        "한국관광공사",
        "https://apis.data.go.kr/B551011/EngService2",
        "https://www.data.go.kr/data/15101753/openapi.do",
        "json_xml_api",
        "public_data_service_key",
        "C",
        supported_languages=("en",),
    ),
    SourceDefinition(
        "SRC_TOUR_JA",
        "한국관광공사",
        "https://apis.data.go.kr/B551011/JpnService2",
        "https://www.data.go.kr/data/15101760/openapi.do",
        "json_xml_api",
        "public_data_service_key",
        "C",
        supported_languages=("ja",),
    ),
    SourceDefinition(
        "SRC_TOUR_ZH_CN",
        "한국관광공사",
        "https://apis.data.go.kr/B551011/ChsService2",
        "https://www.data.go.kr/data/15101764/openapi.do",
        "json_xml_api",
        "public_data_service_key",
        "C",
        supported_languages=("zh-CN",),
    ),
    SourceDefinition(
        "SRC_KTO_PLACE_HUB",
        "한국관광공사",
        "https://apis.data.go.kr/B551011/LocgoHubTarService1",
        "https://www.data.go.kr/data/15128559/openapi.do",
        "json_xml_api",
        "public_data_service_key",
        "C",
    ),
    SourceDefinition(
        "SRC_KTO_PLACE_RELATED",
        "한국관광공사",
        "https://apis.data.go.kr/B551011/TarRlteTarService1",
        "https://www.data.go.kr/data/15128560/openapi.do",
        "json_xml_api",
        "public_data_service_key",
        "C",
    ),
    SourceDefinition(
        "SRC_SEMAS_SHOPS",
        "소상공인시장진흥공단",
        "https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInRadius",
        "https://www.data.go.kr/data/15012005/openapi.do",
        "json_xml_api",
        "public_data_service_key",
        "C",
    ),
    SourceDefinition(
        "SRC_KTO_VISITOR_FORECAST",
        "한국관광공사",
        "https://apis.data.go.kr/B551011/TatsCnctrRateService",
        "https://www.data.go.kr/data/15128555/openapi.do",
        "json_xml_api",
        "public_data_service_key",
        "B",
    ),
    SourceDefinition(
        "SRC_KMA_FORECAST",
        "기상청",
        "https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0",
        "https://www.data.go.kr/data/15084084/openapi.do",
        "json_xml_api",
        "public_data_service_key",
        "B",
    ),
    SourceDefinition(
        "SRC_FESTIVAL",
        "행정안전부",
        "https://api.data.go.kr/openapi/tn_pubr_public_cltur_fstvl_api",
        "https://www.data.go.kr/data/15013104/standard.do",
        "json_xml_api",
        "public_data_service_key",
        "B",
    ),
    SourceDefinition(
        "SRC_HOLIDAY",
        "한국천문연구원",
        "https://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService",
        "https://www.data.go.kr/data/15012690/openapi.do",
        "json_xml_api",
        "public_data_service_key",
        "E",
    ),
    SourceDefinition(
        "SRC_TOURISM_ADMISSION",
        "한국문화관광연구원",
        "https://apis.data.go.kr/B551011/TourismResourceStatsService",
        "https://www.data.go.kr/data/15000366/openapi.do",
        "json_xml_api",
        "public_data_service_key",
        "D",
    ),
    SourceDefinition(
        "SRC_KTO_INBOUND_STATS",
        "한국관광공사",
        "https://datalab.visitkorea.or.kr",
        "https://datalab.visitkorea.or.kr/datalab/portal/ts/getEntcnyFrgnCust2Form.do",
        "html_or_file",
        "public",
        "D",
        storage_mode="content",
    ),
    SourceDefinition(
        "SRC_AIRPORT_COUNTRY",
        "인천국제공항공사",
        "https://apis.data.go.kr/B551177/AviationStatsByCountry",
        "https://www.data.go.kr/data/15095071/openapi.do",
        "json_xml_api",
        "public_data_service_key",
        "D",
    ),
    SourceDefinition(
        "SRC_AIRPORT_WEEKLY",
        "인천국제공항공사",
        "https://apis.data.go.kr/B551177/PaxFltSched",
        "https://www.data.go.kr/data/15095059/openapi.do",
        "json_xml_api",
        "public_data_service_key",
        "A",
    ),
    SourceDefinition(
        "SRC_KEXIM_FX",
        "한국수출입은행",
        "https://oapi.koreaexim.go.kr/site/program/financial/exchangeJSON",
        "https://www.data.go.kr/data/3068846/openapi.do",
        "json_api",
        "api_key",
        "B",
    ),
    SourceDefinition(
        "SRC_BOK_ECOS",
        "한국은행",
        "https://ecos.bok.or.kr/api",
        "https://ecos.bok.or.kr/api/",
        "json_xml_api",
        "api_key",
        "D",
    ),
    SourceDefinition(
        "SRC_EMBASSY_NOTICE",
        "대한민국 재외공관 및 등록 해외 공식기관",
        "https://www.mofa.go.kr",
        "https://www.mofa.go.kr/www/wpge/m_20347/contents.do",
        "rss_html_allowlist",
        "public",
        "A",
        storage_mode="content",
        content_policy=(
            "Sanitize and retain official notice text and revision history indefinitely."
        ),
        supported_countries=(),
        supported_languages=(),
    ),
    SourceDefinition(
        "SRC_KETA",
        "대한민국 법무부",
        "https://www.k-eta.go.kr",
        "https://www.k-eta.go.kr/",
        "html_allowlist",
        "public",
        "A",
        storage_mode="content",
    ),
    SourceDefinition(
        "SRC_KTO_MARKET_TREND",
        "한국관광공사",
        "https://datalab.visitkorea.or.kr",
        "https://datalab.visitkorea.or.kr/site/portal/ex/bbs/List.do?cbIdx=1132",
        "html_allowlist",
        "public",
        "A",
        storage_mode="content",
    ),
)


CADENCE_SECONDS = {
    "A": (3600, 3 * 3600),
    "B": (6 * 3600, 18 * 3600),
    "C": (24 * 3600, 3 * 24 * 3600),
    "D": (24 * 3600, 38 * 24 * 3600),
    "E": (7 * 24 * 3600, 30 * 24 * 3600),
}


def source_definition(source_id: str) -> SourceDefinition:
    try:
        return next(item for item in SOURCES if item.source_id == source_id)
    except StopIteration as exc:
        raise KeyError(source_id) from exc
